{{- if .Values.serviceAccount.create -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service-account
  labels:
    app: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
{{ (include "serviceAccountAnnotations" .) | indent 4 }}
{{- end }}